version: '3.8'

services:
  postgres:
    image: apache/age:latest
    container_name: postgres_age
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_app
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  pgdata:
  pgadmin_data: